# include <iostream>

int main(int argc, char const *argv[]) {
    
    // Errors and Warnings.
    // There are 3 Kinds of Errors and Warnings.
    // 1. Compile Time Errors.
    // 2. Runtime Errors.
    // 3. Warning.

    // Compile Time Errors.
        // As a C++ Programmer, out main goal is to successfully compile our c++ code and get the binary generated by the compiler.
        // The Compiler set some rules for us to follow in our C++ code.
        // If we don't follow these rules, the compiler complaints us and rejects to compile.
        // So we need to fix our code according to what compiler is saying.
        // These type of errors are called compile time errors.
        // For Example:
            // If we forget to put a semicolon (;) at the end of a line in C++, Compiler will throw an error with a error message. By understanding the error message, we need to know that there is something wrong in our code. (Syntax) so when we fix, The compiler will happily compiles our code and generate binary.

    // Runtime Errors.
        // Runtime errors are the errors which occur after the compiling.
        // They have more to with the binary.
        // For Example:
            // Let's say you want to print your name on the screen, and it is not doing it.
        // Runtime Errors are kind of Logical Errors.
        // There's something wrong with the logic of the program.
        // Sometimes Runtime errors may cause the program to crash or terminate.
        
        // Warnings.
        // Warnings are kind of error which is not quite serious to a compiler.
        // But also then, compiler will throw the warning message because it is better to solve it.
        // Compiler tells that this can cause a big program so please fix it now.
        // But The code will compile.

    return 0;
}