# include <iostream>

int main(int argc, char const *argv[]) {

    // C++ Program Execution Model.
        // After we compile the program, a binary file generated by the compiler. Which we cannot read through our human eyes.
        // Binary is the file which meant to be read by program not by IDEs or Code Editors.

        // Why Binary?
            // Because Binary format is easily understandable the CPU.
        
        // After we run our Binary, the binary file form hard drive, its data go inside RAM and then it allocates the memory, set the variables.. etc.. and then CPU process our program from RAM.

        

    return 0;
}